---
author: Dan Kelley, Jaimie Harbin, ...
title: Exploration of ways to trim ctd profiles
---

# sbe2 (DK)

```{r}
library(oce)
d0 <- read.oce("SBE19plus_01906009_2019_04_11.cnv")

sbe2 <- function(data, parameters=NULL)
{
    debug <- 1 # causes message and plotting
    p <- data$pressure
    if (is.null(parameters))
        parameters <- list()
    if (is.null(parameters$minSoak))
        parameters$minSoak <- 1
    if (is.null(parameters$maxSoak))
        parameters$maxSoak <- 20
    if (is.null(parameters$toleranceSoak))
        parameters$toleranceSoak <- 1
    # Need descent speed to exceed mean+descentFactor(std dev)
    if (is.null(parameters$descentFactor))
        parameters$descentFactor <- 2
    if (parameters$maxSoak <= parameters$minSoak)
        stop("require minSoak < maxSoak")
    # Find most common pressure that is within the indicated range
    keep <- parameters$minSoak <= p & p <= parameters$maxSoak
    h <- hist(p[keep], breaks=sum(keep)/10, plot=FALSE) # FIXME: 10 is a guess
    pSoak <- h$mids[which.max(h$counts)]
    if (is.null(parameters$toleranceSoak))
        parameters$toleranceSoak <- 1
    pSoakMin <- pSoak - parameters$toleranceSoak
    pSoakMax <- pSoak + parameters$toleranceSoak
    # Find indices of pressures in soaking range
    soaking <- pSoakMin <= p & p <= pSoakMax
    # Debugging plots
    if (debug > 0L) {
        oceDebug(debug, vectorShow(pSoak))
        oceDebug(debug, vectorShow(pSoakMin))
        oceDebug(debug, vectorShow(pSoakMax))
        abline(h=pSoak, col=4)
        abline(h=pSoakMin, col=4)
        abline(h=pSoakMax, col=4)
        abline(h=parameters$minSoak, col=4, lty="dotted")
        abline(h=parameters$maxSoak, col=4, lty="dotted")
    }
    # Use runlength to find pre-soak and soak intervals at the start
    rleSoak <- rle(soaking)
    startSoak <- rleSoak$lengths[1]
    endSoak <- startSoak + rleSoak$lengths[2]
    if (debug > 0L) {
        oceDebug(debug, vectorShow(startSoak))
        oceDebug(debug, vectorShow(endSoak))
        abline(v=startSoak, col=4)
        abline(v=endSoak, col=4)
    }
    np <- length(p)
    keep <- rep(TRUE, np)
    # Ignore pre-soak and soak
    keep[1:endSoak] <- FALSE
    # Ignore data after max depth found (i.e. ignore upcast)
    deepest <- which.max(p)
    if (debug > 0L) {
        oceDebug(debug, vectorShow(deepest))
        abline(v=deepest, col=2)
    }
    keep[deepest:np] <- FALSE
    # Trim ascent from soaking depth to the surface
    shallowest <- which.min(p[keep]) + which(keep)[1]
    oceDebug(debug, vectorShow(shallowest))
    if (debug > 0L) {
        abline(v=shallowest, col=2)
    }
    keep[1:shallowest] <- FALSE
    # Trim slow descents
    dp0 <- smooth(diff(p[keep]))
    sinking <- dp0[dp0 > 0]
    #hist(sinking, breaks=50);abline(v=mean(sinking),col=4)
    #abline(v=quantile(sinking), col=2)
    #message(vectorShow(mean(sinking)))
    #message(vectorShow(sd(sinking)))
    #message(vectorShow(mean(sinking)-sd(sinking)))
    #message(vectorShow(mean(sinking)-2*sd(sinking)))
    #abline(v=mean(sinking)-2*sd(sinking), lwd=3)
    #plot(sinking > mean(sinking)-2*sd(sinking))
    dp <- diff(smooth(p))
    dp <- c(dp[1], dp)
    sinkingFast <- dp > mean(sinking) - parameters$descentFactor * sd(sinking)
    #message(vectorShow(dp))
    #message(vectorShow(sinkingFast))
    #message(vectorShow(keep))
    keep <- keep & sinkingFast
    keep
}
plotScan(d0, type="p", pch=20, cex=0.2)
keep <- sbe2(d0@data)
points(seq_along(d0[["pressure"]]), d0[["pressure"]],
    pch=20, cex=0.5, col=ifelse(keep, 2, 1))
```



# removeDowncast (JH)

```{r}
library(oce)
f <- read.oce("SBE19plus_01906009_2019_04_11.cnv")
par(mfrow=c(1,2))
plotScan(f)
max <- which(round(f[['pressure']],0) == max(round(f[['pressure']],0)))[1] # Find first rounded max
abline(v=max, col="blue")

trimByIndex<-function(data, parameters, debug) {
  parameters[1] < data$scan & data$scan < parameters[2]
}
removeUpcast <- function(x) {
  # x is an oce ctd object
  max <- which(round(x[['pressure']],0) == max(round(x[['pressure']],0)))[1] # Find first rounded max
  # Removing upcast
  clean <- ctdTrim(x, trimByIndex, parameters=c(0, max))
  return(clean)
}
f2 <- removeUpcast(f)
plotScan(f2)
```




