library(oce)
library(testthat)
context("Plotting")
test_that("multi-panel plots leave usr as it was originally", {
          skip_on_cran()
          data(adp)
          plot(adp)
          expect_equal(par('usr'), c(0, 1, 0, 1))
          data(adv)
          plot(adv)
          expect_equal(par('usr'), c(0, 1, 0, 1))
          data(cm)
          plot(cm)
          expect_equal(par('usr'), c(0, 1, 0, 1))
          data(ctd)
          plot(ctd)
          expect_equal(par('usr'), c(0, 1, 0, 1))
          data(lisst)
          plot(lisst)
          expect_equal(par('usr'), c(0, 1, 0, 1))
          data(lobo)
          plot(lobo)
          expect_equal(par('usr'), c(0, 1, 0, 1))
          data(rsk)
          plot(rsk)
          expect_equal(par('usr'), c(0, 1, 0, 1))
          data(sealevel)
          plot(sealevel)
          expect_equal(par('usr'), c(0, 1, 0, 1))
          data(section)
          plot(section)
          expect_equal(par('usr'), c(0, 1, 0, 1))
})
