library(oce)
context("Plotting")
test_that("multi-panel plots leave usr as it was originally", {
          skip_on_cran()
          orig <- par('usr')
          data(adp)
          plot(adp)
          expect_equal(par('usr'), orig)
          data(adv)
          plot(adv)
          expect_equal(par('usr'), orig)
          data(cm)
          plot(cm)
          expect_equal(par('usr'), orig)
          data(ctd)
          expect_warning(plot(ctd), "CTD plots will have better coastlines after")
          expect_equal(par('usr'), orig)
          data(lisst)
          plot(lisst)
          expect_equal(par('usr'), orig)
          data(lobo)
          plot(lobo)
          expect_equal(par('usr'), orig)
          data(rsk)
          plot(rsk)
          expect_equal(par('usr'), orig)
          data(sealevel)
          plot(sealevel)
          expect_equal(par('usr'), orig)
          data(section)
          plot(section)
          expect_equal(par('usr'), orig)
})
