---
title: "Questions for Nortek re AD2CP Format"
author: "Dan Kelley"
date: "2022-07-11"
output: pdf_document
---

# Questions regarding the AD2CP format

1. **Question:** Within a given AD2CP file, if the first instance of type "X"
   (say, "burst" type, "average" type, etc.) has a particular configuration,
   then can we assume that all the other instances of that type in that file
   will have identical configuration? For example, if echosounder data are
   present in the first instance of "burst", will they be present in all the
   others?

   **Background:** If so, then oce can use vectorized code, which is important
   for speed and code simplicity.

2. **Question:** How are checksums to be calculated, in modern C, i.e. phrased
   in terms of e.g. `uint16`, rather than `unsigned short`?

   **Background:** I have seen manuals with two different expressions of the
   checksum calculation. The scheme used in oce, which has been in-place for
   many years and used often for several types of Nortek files, fails for test
   file `S102791A002_Barrow_v2_avgd.ad2cp`^[The test files are in the
   `tests/testthat/local_data` directory of the "develop" branch of the
   repository at http://www.github.com/dankelley/oce.].

3. **Question:** What is data-chunk-type `0x23`?

   **Background:** Oce detects this in test file `ad2cp_01.ad2cp`$^1$,
   but the string `0x23` is not present in either of the first two documents
   cited below, and is not identified as what oce calls a "chunk type" in
   the third document.

4. **Question:** is there documentation on files with 12-byte headers?

   **Background:** Test file `ad2cp_01.ad2cp`$^1$ has this format.

# References

Nortek AS. “Signature Integration 55|250|500|1000kHz (2017).” Nortek AS, 2017.

Nortek AS. “Signature Integration 55|250|500|1000kHz (2018).” Nortek AS, 2018.

Nortek AS. “Signature Integration 55|250|500|1000kHz (2022).” Nortek AS, March
31, 2022.




