# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

do_approx3d <- function(x, y, z, f, xout, yout, zout) {
    .Call(`_oce_do_approx3d`, x, y, z, f, xout, yout, zout)
}

do_matrix_smooth <- function(mat) {
    .Call(`_oce_do_matrix_smooth`, mat)
}

do_oce_convolve <- function(x, f, end) {
    .Call(`_oce_do_oce_convolve`, x, f, end)
}

do_oce_filter <- function(x, a, b) {
    .Call(`_oce_do_oce_filter`, x, a, b)
}

do_runlm <- function(x, y, xout, window, L) {
    .Call(`_oce_do_runlm`, x, y, xout, window, L)
}

do_trap <- function(x, y, type) {
    .Call(`_oce_do_trap`, x, y, type)
}

