# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matrix_smooth <- function(mat) {
    .Call(`_oce_matrix_smooth`, mat)
}

trap <- function(x, y, type) {
    .Call(`_oce_trap`, x, y, type)
}

